name: e2e-test

on:
  push:
    paths-ignore:
      - "doc/**"
      - "html/**"
      - "**.md"
      - "THANKS"
      - "LICENSE"
      - "NOTICE"

jobs:
  e2e-test-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y ffmpeg v4l2loopback-dkms v4l2loopback-utils linux-modules-extra-$(uname -r)
      - run: |
          curl -LO https://github.com/shiguredo/momo/releases/download/2023.1.0/momo-2023.1.0_ubuntu-22.04_x86_64.tar.gz
          tar -xzf momo-2023.1.0_ubuntu-22.04_x86_64.tar.gz
          mkdir -p _build/ubuntu-22.04_x86_64/release
          chmod 755 momo-2023.1.0_ubuntu-22.04_x86_64/momo
          mv momo-2023.1.0_ubuntu-22.04_x86_64/momo ${{ github.workspace }}/_build/ubuntu-22.04_x86_64/release/
      - uses: eifinger/setup-rye@v3
        with:
          version: 'latest'
      - run: rye sync
        working-directory: ./test
      - run: |
          sudo modprobe v4l2loopback devices=1 video_nr=0 exclusive_caps=1 card_label='VCamera'
          rye run pytest test_momo.py -s
        working-directory: ./test