name: e2e-test

on:
  push:
    paths-ignore:
      - "doc/**"
      - "html/**"
      - "**.md"
      - "THANKS"
      - "LICENSE"
      - "NOTICE"

jobs:
  e2e-test-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos_arm64
    name: Build momo for ${{ matrix.name }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y v4l2loopback-dkms
          sudo modprobe v4l2loopback devices=1 video_nr=0 exclusive_caps=1 card_label='VCamera'
      - run: python3 run.py ubuntu-24.04_x86_64
      - uses: eifinger/setup-rye@v3
        with:
          version: 'latest'
      - run: rye sync
        working-directory: ./test
      - run: rye run pytest test_momo.py
        working-directory: ./test